"""Export generators for DOCX, PPTX, JSON, and CSV formats."""

import csv
import io
import json
from datetime import datetime, timezone
from typing import Any

from docx import Document
from pptx import Presentation
from pptx.util import Inches as PptxInches


def build_report_data(project: dict, data: dict) -> dict[str, Any]:
    """Build the full report data structure from project and all related records."""
    return {
        "meta": {
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "project_name": project.get("name", ""),
            "project_description": project.get("description", ""),
        },
        "project": project,
        "assets": data.get("assets", []),
        "evidence": data.get("evidence", []),
        "codes": data.get("codes", []),
        "themes": data.get("themes", []),
        "requirements": data.get("requirements", []),
        "questionnaire_results": data.get("questionnaire_results", []),
        "design_insights": data.get("design_insights", []),
        "prototype_reviews": data.get("prototype_reviews", []),
        "concept_designs": data.get("concept_designs", []),
        "expert_feedback": data.get("expert_feedback", []),
        "agent_runs": data.get("agent_runs", []),
        "report_sections": data.get("report_sections", _default_sections(data)),
    }


def _default_sections(data: dict) -> list[dict]:
    """Generate default report sections from available data."""
    sections: list[dict] = []
    sections.append(
        {
            "title": "1. Introduction",
            "content": "Workshop analysis report generated by Nano Workshop Agent.",
        }
    )
    sections.append(
        {
            "title": "2. Workshop Methodology",
            "content": "Mixed-methods approach combining qualitative coding, thematic analysis, quantitative statistics, and design insight generation.",
        }
    )

    assets = data.get("assets", [])
    if assets:
        sections.append(
            {
                "title": "3. Data Sources",
                "content": f"{len(assets)} assets processed: "
                + ", ".join(a.get("filename", "") for a in assets[:10]),
            }
        )

    evidence = data.get("evidence", [])
    if evidence:
        sections.append(
            {
                "title": "4. Preprocessing Pipeline",
                "content": f"{len(evidence)} evidence records extracted from source materials.",
            }
        )

    codes = data.get("codes", [])
    themes = data.get("themes", [])
    if codes or themes:
        text = f"{len(codes)} codes applied. " if codes else ""
        text += f"{len(themes)} themes identified."
        sections.append({"title": "5. Qualitative Analysis", "content": text})

    qr = data.get("questionnaire_results", [])
    if qr:
        text = f"{len(qr)} questionnaire(s) analyzed with {sum(q.get('respondent_count', 0) for q in qr)} total respondents."
        sections.append({"title": "6. Quantitative Analysis", "content": text})

    insights = data.get("design_insights", [])
    if insights:
        text = f"{len(insights)} design insights generated."
        sections.append({"title": "7. Design Insights", "content": text})

    proto = data.get("prototype_reviews", [])
    if proto:
        text = f"{len(proto)} prototype(s) reviewed."
        sections.append({"title": "8. Prototype Review", "content": text})

    fb = data.get("expert_feedback", [])
    if fb:
        text = f"{len(fb)} expert feedback records processed."
        sections.append({"title": "9. Expert Feedback and Iteration", "content": text})

    concepts = data.get("concept_designs", [])
    if concepts:
        text = f"{len(concepts)} design concepts created."
        sections.append({"title": "10. Design Guidelines", "content": text})

    sections.append(
        {
            "title": "11. Conclusion",
            "content": "See design guidelines and recommendations above for next steps.",
        }
    )
    sections.append(
        {"title": "12. Appendix", "content": "Full data tables available in CSV and JSON exports."}
    )
    return sections


def generate_docx(report: dict) -> bytes:
    """Generate a Word document from report data."""
    doc = Document()

    # Title
    title = doc.add_heading(report["meta"]["project_name"], 0)
    title.alignment = 1  # center
    doc.add_paragraph(report["meta"].get("project_description", ""))
    doc.add_paragraph(f"Generated: {report['meta']['generated_at']}")

    # Sections
    for section in report.get("report_sections", []):
        doc.add_heading(section["title"], level=1)
        doc.add_paragraph(section.get("content", ""))

    # Data tables
    codes = report.get("codes", [])
    if codes:
        doc.add_heading("Codes", level=2)
        table = doc.add_table(rows=1, cols=3)
        table.style = "Light Grid Accent 1"
        hdr = table.rows[0].cells
        hdr[0].text = "Name"
        hdr[1].text = "Description"
        hdr[2].text = "Evidence Count"
        for c in codes:
            row = table.add_row().cells
            row[0].text = c.get("name", "")
            row[1].text = (c.get("description") or "")[:200]
            row[2].text = str(len(c.get("evidence_ids", [])))

    themes = report.get("themes", [])
    if themes:
        doc.add_heading("Themes", level=2)
        table = doc.add_table(rows=1, cols=3)
        table.style = "Light Grid Accent 1"
        hdr = table.rows[0].cells
        hdr[0].text = "Name"
        hdr[1].text = "Description"
        hdr[2].text = "Confidence"
        for t in themes:
            row = table.add_row().cells
            row[0].text = t.get("name", "")
            row[1].text = (t.get("description") or "")[:200]
            row[2].text = f"{t.get('confidence', 0):.2f}" if t.get("confidence") else "--"

    reqs = report.get("requirements", [])
    if reqs:
        doc.add_heading("Requirements", level=2)
        table = doc.add_table(rows=1, cols=3)
        table.style = "Light Grid Accent 1"
        hdr = table.rows[0].cells
        hdr[0].text = "Text"
        hdr[1].text = "Priority"
        hdr[2].text = "Status"
        for r in reqs:
            row = table.add_row().cells
            row[0].text = r.get("text", "")[:300]
            row[1].text = r.get("priority", "")
            row[2].text = r.get("status", "")

    buf = io.BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf.read()


def generate_pptx(report: dict) -> bytes:
    """Generate a PowerPoint presentation from report data."""
    prs = Presentation()
    prs.slide_width = PptxInches(10)
    prs.slide_height = PptxInches(7.5)

    # Title slide
    slide = prs.slides.add_slide(prs.slide_layouts[0])
    slide.shapes.title.text = report["meta"]["project_name"]
    if slide.placeholders[1]:
        slide.placeholders[1].text = "Workshop Analysis Report"

    # Agenda
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    slide.shapes.title.text = "Structure"
    items = [
        "Workshop Background & Research Goal",
        "Participants and Materials",
        "Key Findings",
        "User Needs Themes",
        "Quantitative Results",
        "Design Requirement Matrix",
        "Prototype Refinement",
        "Design Concepts",
        "Guidelines",
        "Next Steps",
    ]
    body = slide.shapes.placeholders[1].text_frame
    for item in items:
        p = body.add_paragraph()
        p.text = f"• {item}"

    # Data slides
    assets = report.get("assets", [])
    if assets:
        slide = prs.slides.add_slide(prs.slide_layouts[1])
        slide.shapes.title.text = "Participants and Materials"
        body = slide.shapes.placeholders[1].text_frame
        body.text = f"{len(assets)} assets processed"
        for a in assets[:8]:
            p = body.add_paragraph()
            p.text = f"• {a.get('filename', '')} ({a.get('asset_type', '')})"

    themes = report.get("themes", [])
    if themes:
        slide = prs.slides.add_slide(prs.slide_layouts[1])
        slide.shapes.title.text = "User Needs Themes"
        body = slide.shapes.placeholders[1].text_frame
        body.text = f"{len(themes)} themes identified"
        for t in themes:
            p = body.add_paragraph()
            p.text = f"• {t.get('name', '')} (confidence: {t.get('confidence', 0):.2f})"

    qr = report.get("questionnaire_results", [])
    if qr:
        slide = prs.slides.add_slide(prs.slide_layouts[1])
        slide.shapes.title.text = "Quantitative Results"
        body = slide.shapes.placeholders[1].text_frame
        body.text = f"{len(qr)} questionnaire(s)"
        for q in qr:
            stats = q.get("descriptive_stats", {})
            p = body.add_paragraph()
            p.text = f"• {q.get('name', '')}: N={q.get('respondent_count', 0)}"
            if stats:
                p2 = body.add_paragraph()
                p2.text = f"  Mean={stats.get('mean', 'N/A'):.2f}, SD={stats.get('std', 'N/A'):.2f}"

    reqs = report.get("requirements", [])
    if reqs:
        slide = prs.slides.add_slide(prs.slide_layouts[1])
        slide.shapes.title.text = "Design Requirement Matrix"
        body = slide.shapes.placeholders[1].text_frame
        body.text = f"{len(reqs)} requirements"
        for r in reqs[:8]:
            p = body.add_paragraph()
            p.text = f"• [{r.get('priority', 'medium')}] {r.get('text', '')[:120]}"

    concepts = report.get("concept_designs", [])
    if concepts:
        slide = prs.slides.add_slide(prs.slide_layouts[1])
        slide.shapes.title.text = "Design Concepts"
        body = slide.shapes.placeholders[1].text_frame
        body.text = f"{len(concepts)} concepts"
        for c in concepts[:6]:
            p = body.add_paragraph()
            p.text = f"• {c.get('name', '')}: {(c.get('description') or '')[:150]}"

    # Next Steps
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    slide.shapes.title.text = "Next Steps"
    body = slide.shapes.placeholders[1].text_frame
    body.text = "Recommended actions:"
    for step in [
        "Validate findings with stakeholders",
        "Iterate on design concepts",
        "Prototype and test",
        "Finalize design guidelines",
        "Prepare final report",
    ]:
        p = body.add_paragraph()
        p.text = f"• {step}"

    buf = io.BytesIO()
    prs.save(buf)
    buf.seek(0)
    return buf.read()


def generate_json_export(report: dict) -> bytes:
    """Generate a JSON metadata export."""
    serializable = _make_serializable(report)
    return json.dumps(serializable, indent=2, ensure_ascii=False, default=str).encode("utf-8")


def generate_csv_tables(data: dict) -> dict[str, bytes]:
    """Generate CSV files for each data table."""
    tables: dict[str, bytes] = {}

    tables["codes"] = _csv_from_dicts(
        data.get("codes", []), ["name", "description", "evidence_ids"]
    )
    tables["themes"] = _csv_from_dicts(
        data.get("themes", []), ["name", "description", "code_ids", "evidence_ids", "confidence"]
    )
    tables["requirements"] = _csv_from_dicts(
        data.get("requirements", []), ["text", "priority", "source_evidence_ids", "status"]
    )
    tables["questionnaire_stats"] = _csv_from_dicts(
        data.get("questionnaire_results", []),
        ["name", "respondent_count", "scales", "descriptive_stats"],
    )
    tables["expert_feedback"] = _csv_from_dicts(
        data.get("expert_feedback", []),
        ["target_type", "target_id", "action", "score", "comment", "review_status"],
    )
    tables["design_insights"] = _csv_from_dicts(
        data.get("design_insights", []),
        ["title", "description", "category", "confidence", "severity"],
    )
    tables["concept_designs"] = _csv_from_dicts(
        data.get("concept_designs", []),
        ["name", "description", "confidence", "review_status"],
    )

    return tables


def _csv_from_dicts(items: list[dict], columns: list[str]) -> bytes:
    buf = io.StringIO()
    writer = csv.DictWriter(buf, fieldnames=columns, extrasaction="ignore")
    writer.writeheader()
    for item in items:
        row = {}
        for col in columns:
            val = item.get(col, "")
            if isinstance(val, (list, dict)):
                val = json.dumps(val)
            row[col] = val
        writer.writerow(row)
    return buf.getvalue().encode("utf-8-sig")


def _make_serializable(obj: Any) -> Any:
    if isinstance(obj, dict):
        return {k: _make_serializable(v) for k, v in obj.items()}
    elif isinstance(obj, list):
        return [_make_serializable(v) for v in obj]
    elif isinstance(obj, datetime):
        return obj.isoformat()
    return obj
